name: CI

on:
  workflow_dispatch:
    inputs:
      pr-number:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

        automerge:
          needs: build
          runs-on: ubuntu-latest

        permissions:
          pull-requests: write
          contents: write
